# Generated by Django 5.1.4 on 2024-12-06 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeConteudo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDisciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('data', models.DateField()),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='desempenhoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numQuestoes', models.IntegerField(default=0, max_length=3)),
                ('acertos', models.IntegerField(default=0, max_length=3)),
                ('erros', models.IntegerField(default=0, max_length=3)),
                ('periodo', models.DateField()),
                ('Conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conteudo')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='Disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina'),
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ProvaVestibular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.edital'),
        ),
    ]
