# Generated by Django 5.1.4 on 2024-12-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='data',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='edital',
        ),
        migrations.AddField(
            model_name='edital',
            name='titulo',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='desempenhoconteudo',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desempenhoconteudo',
            name='erros',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desempenhoconteudo',
            name='numQuestoes',
            field=models.IntegerField(default=0),
        ),
    ]
